dist: trusty
sudo: true

language: go

go:
 - "1.12"

notifications:
  email: false

addons:
  postgresql: "9.5"

env:
  matrix:
  - KONG_VERSION=1.0.3 GOPROXY=https://gocenter.io GO111MODULE=on
  - KONG_VERSION=1.1.2 GOPROXY=https://gocenter.io GO111MODULE=on
  - KONG_VERSION=1.2.0 GOPROXY=https://gocenter.io GO111MODULE=on
  - KONG_VERSION=1.3.0rc1 GOPROXY=https://gocenter.io GO111MODULE=on

before_install:
  - psql -c 'create database kong;' -U postgres
  - psql -c 'create user kong;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE "kong" to kong;' -U postgres

install:
  - bash .ci/setup_kong.sh
  - ./hack/verify-deepcopy-gen.sh

